// Placeholder Firebase options file.
// Replace this file with the one generated by `flutterfire configure`.
// The generated file will include platform-specific Firebase configs.

class DefaultFirebaseOptions {
  static void ensureConfigured() {
    throw UnimplementedError(
      'Replace firebase_options.dart with the generated version from flutterfire configure.',
    );
  }

  static dynamic get currentPlatform => ensureConfigured();
}
